Adding check for failure in scripts that have multiple sfdx commands

diff --git a/mkclass b/mkclass
--- a/mkclass
+++ b/mkclass
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+function fail {
+	echo "ERROR: $@"
+	exit 1
+}
+
 if [[ $# -eq 1 ]]
 then
 	class_name=$1
@@ -15,9 +20,11 @@ else
 fi
 
 echo "sfdx force:apex:class:create -n ${class_name} -d ${classes_dir}"
-sfdx force:apex:class:create -n ${class_name} -d ${classes_dir}
+sfdx force:apex:class:create -n ${class_name} -d ${classes_dir} || \
+	fail "Could not create class"
 echo "sfdx force:apex:class:create -n ${class_name}Test -d ${classes_dir}"
-sfdx force:apex:class:create -n ${class_name}Test -d ${classes_dir}
+sfdx force:apex:class:create -n ${class_name}Test -d ${classes_dir} || \
+	fail "Could not create test class"
 
 
 
diff --git a/mktrigger b/mktrigger
--- a/mktrigger
+++ b/mktrigger
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+function fail {
+	echo "ERROR: $@"
+	exit 1
+}
+
 if [[ $# -eq 1 ]]
 then
 	trigger_name=$1
@@ -23,9 +28,11 @@ else
 fi
 
 echo "sfdx force:apex:trigger:create -n $trigger_name -s $object_name -d $trigger_dir"
-sfdx force:apex:trigger:create -n $trigger_name -s $object_name -d $trigger_dir
+sfdx force:apex:trigger:create -n $trigger_name -s $object_name -d $trigger_dir || \
+	fail "Could not create trigger"
 echo "sfdx force:apex:class:create -n ${trigger_name}Test -d $classes_dir"
-sfdx force:apex:class:create -n ${trigger_name}Test -d $classes_dir
+sfdx force:apex:class:create -n ${trigger_name}Test -d $classes_dir || \
+	fail "Could not create trigger test class"
 
 
 
